### ISSUE TITLE
Firmware filename is to long

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#132]
Some routers have filename length limits in the stock firmware. The current naming scheme can result in filenames which are to long to be flashed to these routers without renaming.

**Comment by Jo-Jo0** [comment]
Saw this on tl-wr841 v10 today

**Comment by Moorviper** [comment]
<60 zeichen muss der Dateiname sein

**Comment by fooker** [comment]
Even removing the build date from the filename would not solve this issue.

**Comment by Moorviper** [comment]
Ich würde das gluon entfernen + anstatt stable ein einfaches s verwenden
u = u stable
t = testing

Spart ca 10 Zeichen

Datum und Uhrzeit ist meiner Meinung nach schon wichtig

**Comment by SISheogorath** [comment]
`gluon-fffd-4-220-20160330103617-stable-tp-link-tl-wa701n-nd-v2.bin` is the longest firmware name for TP-Link (everything else is not important because no issues are reported from others).

Removing timestamp, would work (51 chars). Removing Firmware version works too (it's not needed really because we have a build number) and changing stable to s strips the string down to 44 chars.

**Comment by fooker** [comment]
Merged to development
