### ISSUE TITLE
Gluon upgrade

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#44]
Upgrade to gluon 2015.1.1

**Comment by indigo423** [comment]
Lösungsvorschlag in PR freifunk-fulda/gluon#6

**Comment by SISheogorath** [comment]
we fixed that issue with https://github.com/freifunk-fulda/site-fffd/pull/6

Firmware is building using https://github.com/freifunk-gluon/gluon/tree/v2015.1.2 so we can delete our gluon fork as it's not needed. We just maintain it for nothing because we don't change anything in there. And if we want we can still use https://github.com/freifunk-fulda/fffd-packages and https://github.com/freifunk-fulda/site-fffd. So no need to maintain a merge only fork.

**Comment by fooker** [comment]
ab v2015 sind die gluon-spezifischen Packete Teil des Repos. Wir brauchen dann also eine Möglichkeit für Änderungen an Texten u.ä.

**Comment by SISheogorath** [comment]
Laut tcatm ist es keineswegs nötig ein eigenes Repo vor zu halten. Ausschließlich die Site config und eben ggf. noch eigene Package Repos sind zu empfehlen. Mehr aber auch erstmal nicht. Alle zu ändernen Texte werden über die site config geändert. Im Zweifel soll man ihnen einfach mal bescheid geben, wenn es da denn noch irgendwas gibt. 

Aber mir fällt im Moment auch kein Punkt ein, wo man da wirklich mal was brauchen könnte. Selbst für händisches ist es eher empfohlen einfach die site config irgendwo hin zu klonen und dann bei make als parameter an zu geben. Somit ist eigentlich jeder Grund ein eigenes Repo zu halten vershwunden.

**Comment by fooker** [comment]
Hab ich auch herausgefunden. Ok to merge.

## 

-----Original Message-----

**Comment by SISheogorath** [comment]
Ich hab mal i18n Support gebastelt, wenn wir den Brauchen. Aber eigentlich sollte unsere andere Config auch reichen. zumindest ging es damit letzten Montag bestens.

https://github.com/freifunk-fulda/site-fffd/pull/7

**Comment by fooker** [comment]
Development is now building against 2015.1.2
